#
# 您的 Crowdin 凭据
#
project_id: '490937'
api_token: 'CROWDIN_PERSONAL_TOKEN'

#
# 在 Crowdin 中选择文件结构
#
preserve_hierarchy: true

# 我们通常希望使用语言环境（即语言）的“双字母代码”
# 但并非适用于所有地区！
# "pt-BR" 最好保留为 "pt-BR" 而不是转换为 "pt"
# Note: &/* is Yaml anchor syntax: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
languages_mapping: &languages_mapping
  two_letters_code:
    'pt-BR': 'pt-BR'

#
# 文件配置
#
files: [
  {
    source: '/i18n/zh/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%',
    languages_mapping: *languages_mapping,
  },
  {
    source: '/docs/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
    languages_mapping: *languages_mapping,
  },
  {
    source: '/tutorial/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-tutorial/current/**/%original_file_name%',
    languages_mapping: *languages_mapping,
  },
  {
    source: '/tutorial_versioned_docs/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-tutorial/**/%original_file_name%',
    languages_mapping: *languages_mapping,
  },
  {
    source: '/blog/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%',
    languages_mapping: *languages_mapping,
  },
  {
    source: '/src/pages/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%',
    ignore: [ '/**/*.js', '/**/*.jsx', '/**/*.ts', '/**/*.tsx', '/**/*.css' ],
    languages_mapping: *languages_mapping,
  },
]