'use strict';
const test=require('node:test'), assert=require('node:assert/strict');
const fs=require('node:fs'), os=require('node:os'), path=require('node:path');
const {execFileSync}=require('node:child_process');
const {build,load,checkRevisions,digest}=require('../scripts/build-ai-engine-archive.cjs');
const Core=require('../ai-engine-watch/bridge/Core.gs');
function source(overrides={},body='# 测试日报\n\n仅供测试，不是真实资讯。') {
  return '---\n'+JSON.stringify({schema:1,date:'2026-09-11',timezone:'Asia/Shanghai',title:'测试',revision:1,publication:'publish',review_status:'generated',summary:['测试摘要'],events:[],...overrides})+'\n---\n'+body+'\n';
}
function fixture(t) {const root=fs.mkdtempSync(path.join(os.tmpdir(),'archive-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function put(root,text,filename='ai-engine-watch/reports/2026/09/2026-09-11.md'){const p=path.join(root,filename);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text);return p;}
const read=(r,p)=>JSON.parse(fs.readFileSync(path.join(r,'static/ai-engine-watch',p),'utf8'));
test('empty archive is a real empty landing, not a fabricated report',t=>{const r=fixture(t);assert.equal(build(r).reports,0);assert.deepEqual(read(r,'index/recent.json').reports,[]);assert.match(fs.readFileSync(path.join(r,'.generated/ai-engine-watch/index.md'),'utf8'),/暂时没有已发布/)});
test('original, receipt and generated document share a hash',t=>{const r=fixture(t);put(r,source());build(r);const raw=fs.readFileSync(path.join(r,'static/ai-engine-watch/raw/2026/09/2026-09-11.md'),'utf8');const receipt=read(r,'receipts/2026-09-11.json');assert.equal(receipt.sha256,digest(raw));assert.equal(receipt.html,'reports/2026-09-11');assert.ok(fs.readFileSync(path.join(r,'.generated/ai-engine-watch/2026-09-11.md'),'utf8').includes('source-sha256:'+receipt.sha256))});
test('project base path is preserved',t=>{const r=fixture(t);put(r,source());build(r);assert.ok(fs.readFileSync(path.join(r,'.generated/ai-engine-watch/2026-09-11.md'),'utf8').includes('/danyow/ai-engine-watch/raw/'))});
test('alternative base URL is supported without hardcoded origin',t=>{const r=fixture(t);put(r,source());build(r,{baseUrl:'/test/'});assert.ok(fs.readFileSync(path.join(r,'.generated/ai-engine-watch/2026-09-11.md'),'utf8').includes('/test/ai-engine-watch/'))});
test('invalid base path is rejected',t=>assert.throws(()=>build(fixture(t),{baseUrl:'../../'})));
test('held draft is not safe to put in a public repository',t=>{const r=fixture(t);put(r,source({publication:'hold'}));assert.throws(()=>build(r),/HELD_OR_UNVERIFIED/)});
test('unverified import is not published',t=>{const r=fixture(t);put(r,source({review_status:'imported-unverified'}));assert.throws(()=>load(r),/HELD_OR_UNVERIFIED/)});
test('wrong source date path is rejected',t=>{const r=fixture(t);put(r,source(),'ai-engine-watch/reports/2026-09-11.md');assert.throws(()=>load(r),/INVALID_REPORT_PATH/)});
test('symlink source cannot escape archive',t=>{const r=fixture(t);const p=put(r,source());fs.symlinkSync(p,path.join(path.dirname(p),'linked.md'));assert.throws(()=>load(r),/SYMLINK/)});
test('invalid new source does not erase last generated output',t=>{const r=fixture(t);const p=put(r,source());build(r);fs.writeFileSync(p,'invalid');assert.throws(()=>build(r));assert.equal(read(r,'index/catalog.json').total,1)});
test('build leaves unrelated static assets alone',t=>{const r=fixture(t);const p=path.join(r,'static/img/test.svg');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,'original');build(r);assert.equal(fs.readFileSync(p,'utf8'),'original')});
test('monthly and recent indexes do not embed article body',t=>{const r=fixture(t);put(r,source());put(r,source({date:'2026-07-01'}),'ai-engine-watch/reports/2026/07/2026-07-01.md');build(r);assert.equal(read(r,'index/catalog.json').months.length,2);assert.equal(read(r,'index/recent.json').reports.length,1);assert.ok(!JSON.stringify(read(r,'index/2026-09.json')).includes('仅供测试，不是真实资讯'))});
test('repeated build is deterministic',t=>{const r=fixture(t);put(r,source());build(r);const before=JSON.stringify(read(r,'index/recent.json'));build(r);assert.equal(JSON.stringify(read(r,'index/recent.json')),before)});
for(const [name,addition] of [['email','private@example.org'],['webhook','https://open.feishu.cn/open-apis/bot/v2/hook/test'],['script','<script>alert(1)</script>'],['jsx','<Widget />'],['import','\nimport x from "bad"'],['dangerous URL','[x](javascript:alert(1))']]) test('rejects '+name,()=>assert.throws(()=>Core.parse(source({},'# 测试\n'+addition))));
test('event dates and source remain queryable',t=>{const r=fixture(t);put(r,source({events:[{project:'test',title:'测试事件',kind:'code',event_date:'2026-09-10',publication_date:null,discovered_date:'2026-09-11',evidence:'source-claim',source:'https://example.org/release'}]}));build(r);const e=read(r,'index/2026-09.json').events[0];assert.equal(e.evidence,'source-claim');assert.equal(e.publication_date,null);assert.equal(e.report,'ai-engine-watch/reports/2026/09/2026-09-11.md')});
test('changing an archived day requires revision increment',t=>{const r=fixture(t);put(r,source());const git=args=>execFileSync('git',args,{cwd:r,stdio:'pipe',encoding:'utf8'});git(['init','-q']);git(['add','.']);git(['-c','user.name=test','-c','user.email=test@example.invalid','commit','-qm','fixture']);const sha=git(['rev-parse','HEAD']).trim();checkRevisions(r,sha);put(r,source({},'# 修改后的标题'));assert.throws(()=>checkRevisions(r,sha),/INCREMENT_REVISION/);put(r,source({revision:2}));checkRevisions(r,sha)});
test('archive deletion is blocked by history check',t=>{const r=fixture(t);const p=put(r,source());const git=args=>execFileSync('git',args,{cwd:r,stdio:'pipe',encoding:'utf8'});git(['init','-q']);git(['add','.']);git(['-c','user.name=test','-c','user.email=test@example.invalid','commit','-qm','fixture']);const sha=git(['rev-parse','HEAD']).trim();fs.unlinkSync(p);assert.throws(()=>checkRevisions(r,sha),/REPORT_DELETION/)});
