name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn write-translations
          yarn crowdin-uploade
          yarn crowdin-download
          yarn build

#      - name: crowdin action
#        with:
#          # 上传资源选项
#          upload_sources: true
#          # 这可用于传递 `upload sources` cli 命令的任何支持的参数，例如
#          ##upload_sources_args: '--no-auto-update label=web'
#
#          # 上传翻译选项
#          upload_translations: true
#          upload_language: 'zh'
#          auto_approve_imported: true
#          import_eq_suggestions: true
#          # 这可用于传递 `upload translations` cli 命令的任何支持的参数，例如
#          ##upload_translations_args: '--auto-approve-imported --translate-hidden'
#
#          # 下载翻译选项
#          download_translations: true
#          download_language: 'zh'
#          skip_untranslated_strings: true
#          skip_untranslated_files: true
#          export_only_approved: true
#          ##push_translations: true
#          ##commit_message: 'New Crowdin translations by GitHub Action'
#          # 这可用于传递`download translations` cli 命令的任何支持的参数，例如
#          ##download_translations_args: '--all --skip-untranslated-strings'
#
#          # 这是 Crowdin 在打开拉取请求时将创建的 git 分支的名称。
#          # 这个分支不需要手动创建。它将由操作自动创建。
#          ##localization_branch_name: l10n_crowdin_action
#          ##create_pull_request: true
#          ##pull_request_title: 'New Crowdin translations'
#          ##pull_request_body: 'New Crowdin pull request with translations'
#          ##pull_request_labels: 'enhancement, good first issue'
#          # 这是将创建拉取请求的 git 分支的名称。
#          # 如果未指定，将使用默认存储库分支。
#          ##pull_request_base_branch_name: not_default_branch
#
#          # 分支选项
#          add_crowdin_branch: branch_name
#          # 译者眼中的标题
#          new_branch_title: 'development / main'
#          # 在结果翻译包中定义分支名称和路径
#          new_branch_export_pattern: '/translations/%two_letters_code%/%original_file_name%'
#          # [LOW, NORMAL, HIGH]
#          new_branch_priority: 'HIGH'
#
#          delete_crowdin_branch: branch_name
#
#          # 全局选项
#
#          # 这是 Crowdin 将用于文件的顶级目录的名称。
#          # 请注意，这不是 git 意义上的“分支”，而更像是 Crowdin 项目中的顶级目录。
#          # 这个分支不需要手动创建。它将由操作自动创建。
#          crowdin_branch_name: l10n_branch
#          identity: 'path/to/your/credentials/file'
#          config: 'path/to/your/crowdin.yml'
#          dryrun_action: true
#
#          # GitHub (Enterprise) configuration
#
#          github_base_url: github.com
#          github_api_base_url: api.[github_base_url]
#          github_user_name: Crowdin Bot
#          github_user_email: support+bot@crowdin.com
#
#          # 对于签名提交，请添加您的 ASCII 装甲密钥
#          # 确保所有电子邮件都相同：对于持有公钥的帐户配置文件，在密钥生成期间指定的，以及提交作者（github_user_email 参数）
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#
#          # config options
#
#          # 这是一个数字 ID，不要与 Crowdin API v1“项目标识符”字符串混淆
#          # See "API v2" on https://crowdin.com/project/<your-project>/settings#api
#          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
#
#          # 个人访问令牌，不要与 Crowdin API v1“API 密钥”混淆
#          # See https://crowdin.com/settings#api-key to generate a token
#          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
#          source: 'path/to/your/file'
#          translation: 'file/export/pattern'
#          base_url: 'https://crowdin.com'
#          base_path: '/project-base-path'

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com