name: 部署到GitHub

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 部署到GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: 构建网站
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        # 本地化 crowdin-udb
        run: |
          yarn install --frozen-lockfile
          yarn build

      # 目前较为流行部署到GitHubPages 的Action：
      # 文档: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: 部署到GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          # 构建输出以发布到 `gh-pages` 分支：
          publish_dir: ./build
          # 将提交作者身份分配给官方 GH-Actions 机器人以部署到 `gh-pages` 分支：
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # 如果您未指定这两个字段，则默认使用 GH 操作机器人。
          # 您可以使用自己的用户凭据替换它们。
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          cname: danyow.cn

  sync:
    needs: deploy
    name: 同步到Gitee
    runs-on: ubuntu-latest
    steps:
      - name: 同步到Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:danyow/danyow.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:danyow/danyow.git

  gitee:
    needs: sync
    name: 部署Gitee
    runs-on: ubuntu-latest
    steps:
      - name: 部署Gitee
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: danyow
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: danyow/danyow
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
